### ISSUE TITLE
Possible installation issue with ipyvega versions 2.3.0 and 2.2.0 (but 2.1.0 ok)

### ISSUE THREAD

**Issue by ianozsvald** [vega/altair#1562] opened 2019-06-14 16:32 UTC
Tonight, before a conference talk, I figured I'd add a quick Altair plot into my live Notebook demo. This crashed-and-burned for the last hour. I'm logging this "potential issue" in case anyone else can replicate it. If not, possibly I just did something silly, in which case I'll appologise for the noise and we can close off this issue.

What I did:
* created a fresh up-to-date Anaconda environment, Notebook, Pandas, scikit-learn, matplotlib, Altair, vega
* followed: https://altair-viz.github.io/user_guide/troubleshooting.html https://altair-viz.github.io/getting_started/installation.html
* tried to make simple Atair plots but either got the `<VegaLite 3 object>` wrong-renderer issue or a blank output (i.e. `Out[x]` followed by nothing, no errors, just nothing)
* I tried `alt.renderers.enable('notebook')` in my Notebook, no change
* I installed and tried a Jupyter Lab, no change (having removed the renderers.enable line)
* I tried multiple restarts of my kernels, Notebooks and Lab, no change

I checked issues here and on vega (ipyvega github page), nothing popped out. I remember that on my other machine (a Mac), just over a week back, I had Altair installed and working. I downgraded from ipyvega 2.3.0 to 2.2.0 and nothing changed, I downgraded to 2.1.0 and everything worked just fine.

I'll note that vega 2.2.0 was released a week ago and 2.1.0 back in April: https://pypi.org/project/vega/#history

My successful downgrade came via `conda install -c conda-forge vega=2.1.0`

I present tomorrow and I want to show Altair being used for exploratory data work and eyeballing bad-data outliers -  so I'm not going to mess around with this installation any more! I can dig after if that's helpful.

I noted in the title `ipyvega` (https://github.com/vega/ipyvega) - I believe this is the same as `vega` on PyPI but please tell me if I'm wrong, I got a bit lost following vega/vega-lite/ipyvega in this debug trip.

My current (working) configuration:
```
In [1]: import altair                                                                                                                      
In [2]: altair.__version__                                                                                                                 
Out[2]: '3.1.0'

In [3]: import vega                                                                                                                        
In [4]: vega.__version__                                                                                                                   
Out[4]: '2.1.0'

In [6]: altair.schema.SCHEMA_VERSION                                                                                                       
Out[6]: 'v3.3.0'
```

**Comment by jakevdp** [comment] 2019-06-14 16:51
This is due to https://github.com/vega/ipyvega/issues/105, though vega 2.2 should work fine as well.

Sorry for the issue.

**Comment by jakevdp** [comment] 2019-06-14 16:52
cc @domoritz

**Comment by ianozsvald** [comment] 2019-06-14 17:14
Hey @jakevdp, its cool, I didn't want to miss a chance to demo Altair, it is genuinely helping me be more efficient when dealing with new & dirty data. 

Re. 2.2.0 I may not have restarted everything, I can retry this after I've given my talk. Cheers, Ian.

**Comment by jakevdp** [comment] 2019-06-14 17:17
Great to hear! Hopefully we can continue to iron-out these usability issues.

**Comment by domoritz** [comment] 2019-06-14 17:26
Duplicate of https://github.com/altair-viz/altair/issues/1550

**Closed** 2019-06-14 17:28 UTC
Labels: duplicate

**Comment by ianozsvald** [comment] 2019-06-15 17:14
Just to follow-up - I tried 2.2.0 and indeed it works (along with 2.1.0), apologies for the noise yesterday

**Comment by jakevdp** [comment] 2019-06-15 19:12
Thanks – appreciate the detailed report, and thanks to @domoritz for getting the fix out quickly!
