### ISSUE TITLE
Shorthand for repeat operator field definition

### ISSUE THREAD

**Issue by davidanthoff** [vega/altair#882] opened 2018-05-22 04:24 UTC
Maybe ``"~column"`` could translate to ``{"field": {"repeat": "column"}``? And then of course it would also compose with the type and aggregate shorthands.

Mostly bringing this up because I'd like to add something like that to the julia package for vega-lite. So far I have shamelessly copied your shorthand syntax (hope that is ok!), and ideally I'd like to keep using the shorthand syntax that you use in altair.

**Comment by jakevdp** [comment] 2018-05-22 14:41
Interesting thought... currently we use ``alt.repeat('column')``, which I think is pretty concise.

In my experience, the real UI issue with repeat charts is the disconnection between encodings and fields that it produces, because you have to specify the list of fields elsewhere in the chart. It makes sense in terms of the grammar, but not in terms of the UI, and I've not yet figured out a good alternative

**Comment by jakevdp** [comment] 2019-05-30 05:21
Duplicate of #826

**Closed by jakevdp** 2019-05-30 05:21 UTC
Labels: duplicate
