### ISSUE TITLE
3D Scatter Plots

### ISSUE THREAD

**Issue by abstractqqq** [vega/altair#3622] opened 2024-10-01 16:17 UTC
### What is your suggestion?

It would be great to add 3d scatter plots. In data science, it is common to use PCA to reduce dimension of data to 2/3d. I am working on a new data science library with Polars (which integrates with Altair) and so I want to built my data science related plots on top of Altair. 

I believe a mark_points3() will be an appropriate addition to the package.

### Have you considered any alternative solutions?

I couldn't find any 3d examples, so I assume it doesn't exist at this moment.

**Comment by joelostblom** [comment] 2024-10-03 02:49
Thanks for the suggestion! This would need to be added in Vega first (and then Vega-Lite), so it is a duplicate of issue https://github.com/vega/vega/issues/1738. You can join the discussion there as well as see some possible related current solutions.

**Closed by joelostblom** 2024-10-03 02:49 UTC
Labels: enhancement
