### ISSUE TITLE
Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror

### ISSUE THREAD

**Issue by rongcuid** [vega/altair#3636] opened 2024-10-10 23:36 UTC
### What happened?

This seems to have reported before.

In VSCode Python code cell, try to make any Altair plot and run code cell in Jupyter. This error appears:

```
Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror
```

Also, why do I need a CDN to plot locally?

### Which version of Altair are you using?

5.4.1

**Comment by mattijn** [comment] 2024-10-11 12:14
Thank you for the report. 
Regarding your first question.

I cannot reproduce this behavior. The steps I tried:
1. I created a notebook in VS Code and populate it with python code that uses Altair to create a chart.
2. I saved the notebook
3. I open this notebook in Jupyter Lab, and run the same cell. For me, the chart appears identical.

You did follow the same procedure, but it fails for you?

Regarding your second question, 

> why do I need a CDN to plot locally?

Altair produces JSON specifications following Vega-Lite grammar. The "vega-embed" CDN package is required to render this JSON specifications as a visualization. You can find information on this [here](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-altair-charts). 

On that page is explained that there is offline support available for some renderers (eg. `alt.renderers.enable("jupyter", offline=True)`), but there is no such option for the default renderer, something as such `alt.renderers.enable("html", offline=True)`. That might be a potential feature request, not sure if that is actually feasible, do you know if this is a valid feature request @jonmmease?

**Comment by rongcuid** [comment] 2024-10-11 12:54
That was not my procedure:

1. Install Jupyter extension in VSCode
2. Have an example in a code cell:

```py
# %%
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()
```

Use VSCode command to run code cell, which opens an interactive pane and have the error.

**Comment by jonmmease** [comment] 2024-10-11 14:04
> do you know if this is a valid feature request @jonmmease?

It's certainly valid, the tricky thing is that you don't really want to save all of the JavaScript bundles along with every chart in the notebook (the `"jupyter"` renderer doesn't save state in the notebook at all, so this doesn't come up).  There are more complicated workflows that Bokeh and Plotly use where the js bundle is loaded once and then referenced by each chart. But this doesn't work in environments that use `iframe`s like google colab.  So supporting this through the AnyWidget path was much cleaner to start with.

**Comment by rongcuid** [comment] 2024-10-11 14:08
Actually I can't replicate it anymore. I was on a VPN and SSH remote in vscode when that happened.

I'll probably just make jupyter offline my default renderer.

**Comment by mattijn** [comment] 2024-10-14 18:22
Thanks @jonmmease, that makes sense. Let's leave it like this for now! Closing this issue as the issue was an incident.

**Closed** 2024-10-14 18:22 UTC
Labels: bug
