### ISSUE TITLE
Remove PyArrow dependency for Polars support

### ISSUE THREAD

**Issue by MarcoGorelli** [vega/altair#3445] opened 2024-06-26 10:24 UTC
### What is your suggestion?

Currently, PyArrow is required by Altair for Polars support. I think it shouldn't be too hard to remove it, given that Polars implements the dataframe interchange protocol natively (without depending on PyArrow)

If #3384 can make it in, then Altair would actually support plotting Polars dataframe natively without any extra heavy dependencies. That'd be...pretty amazing? I'd suggest using Altair for `polars.DataFrame.plot` if that was the case

I think what would need doing is:
- don't require `pyarrow` to be installed for the `dfi = data.__dataframe__` part
- instead of using `sanitize_arrow_table`, for Polars, just select date/datetime columns and call `.dt.to_string()`
- instead of using `to_pylist` from PyArrow, just use `DataFrame.rows(named=True)` for Polars
- for categoricals, find a non-pyarrow workaround for Polars in `infer_vegalite_type_for_dfi_column`. I haven't tried this yet, but it looks straightforward-ish

Would you open to considering this? Happy to work on a PR if so

### Have you considered any alternative solutions?

Just keep the status-quo :) But, I think Altair is the only plotting library that gets close to native Polars support without extra large dependencies, and it doesn't look like a large stretch to go all the way there, so I'm hoping we can do it 💪 

---

Demo from having tried this locally:

![image](https://github.com/vega/altair/assets/33491632/329cbfc3-e96d-481f-9a7b-855add3b822e)

**Comment by dangotbanned** [comment] 2024-06-26 10:48
Not a maintainer here, but #3426, #3384 and this all landing in the next release sounds great to me - if all goes well

**Comment by mattijn** [comment] 2024-06-26 12:40
Thanks for opening this issue! I'm surely in favor of improving native polars support without relying on a pyarrow dependency.
As you have noticed, we still need to distill existing pandas serialization logic to become more dataframe-agnostic.
 
If I understand right, the suggested change here is to introduce a direct link to polars for a polars DataFrame if that object is compatible with the dataframe interchange protocol?

Eg, some changes here:
https://github.com/vega/altair/blob/76a9ce1e27a21359e7b0ef9e6cb865f8d95fc298/altair/utils/data.py#L406-L408

And here:
https://github.com/vega/altair/blob/76a9ce1e27a21359e7b0ef9e6cb865f8d95fc298/altair/utils/data.py#L406-L416

The introductino of the dataframe interchange protocol is not only for polars, but others are using it too, eg ibis ( https://github.com/vega/altair/issues/3110), or custom objects as in https://github.com/vega/vegafusion/issues/386.

I'm not really in favor of introducing a optional polars dependency, but in line with https://github.com/vega/altair/pull/3377, we are already working towards a direction where we can use direct arrow conversion methods without using the pyarrow from_dataframe interface. If we can improve this direction even more so that pyarrow is not a hard dependency anymore within within the dataframe interchange protocol that would be great.

Simultaneously, I also noticed that vegafusion has recently introduced an alternative approach for serializing objects that are compatible with polars, see eg this part:

https://github.com/vega/vegafusion/blob/007bd44188676de7259bc02a61693b3dc7586072/python/vegafusion/vegafusion/runtime.py#L218-L225

Anyways! PRs in this direction are welcome!

**Comment by mattijn** [comment] 2024-06-26 13:11
First, we try to solve things pragmatic if the dataframe interchange protocol is incomplete. There is not always a royal road. But for my own understanding, isn't this what we are doing already in https://github.com/vega/altair/pull/3377, where we use a direct `to_arrow` method on a dataframe that supports the dataframe interchange protocol?

**Comment by MarcoGorelli** [comment] 2024-06-26 13:15
Yeah, and `to_arrow` requires PyArrow as a dependency :) In the Polars case, Altair is converting Polars to PyArrow, to do things which are already possible (and fairly easy) to do in Polars directly. And that feels like a missed opportunity to keep Altair really lightweight for Polars users who otherwise wouldn't need to bloat their environment up with PyArrow (which is a huge dependency, and not generally required for working with Polars)

**Comment by MarcoGorelli** [comment] 2024-06-26 13:35
Yup, thanks for appreciating the value in this! Alright, PR incoming this week

**Comment by jonmmease** [comment] 2024-06-27 12:45
Hi @MarcoGorelli, just catching up on this thread and on your and @dangotbanned's comments in https://github.com/vega/altair/pull/3384.

I'm all in favor of streamlining polars support in Altair, but I'm less enthused about having polars specific logic scattered around the code base.  On the surface, it seems like narwhals is exactly the kind of abstraction layer we would like in Altair going forward. Could we jump straight to supporting polars without pyarrow using narwhals?  Then ideally over time we could move the other DataFrame types that narwhals supports behind this code path as well.

cc @mattijn, I would personally prefer this approach to making pandas optional, but interested to hear your thoughts.

**Comment by MarcoGorelli** [comment] 2024-06-27 13:00
Thanks for your response!

> On the surface, it seems like narwhals is exactly the kind of abstraction layer we would like in Altair going forward. Could we jump straight to supporting polars without pyarrow using narwhals?

Well, I'm not going to make you ask me twice 😄 Thanks, I'll give this a go and open a PR for your consideration! I don't think it'll be too big of an effort, if you then decide you don't want it, I promise no offense will be taken 😇

**Comment by binste** [comment] 2024-06-27 13:37
Just browsed through the narwhals docs, sounds very interesting! I'm also onboard to allow Polars users to use Altair without the need to have PyArrow or Pandas alongside it.

@MarcoGorelli Thanks for offering to open a PR! Just for you to know, https://github.com/vega/altair/pull/3431 will introduce a lot of changes to the code base. It's almost ready to be merged so you might want to wait a few more days.

**Comment by binste** [comment] 2024-06-27 15:50
> @MarcoGorelli Thanks for offering to open a PR! Just for you to know, #3431 will introduce a lot of changes to the code base. It's almost ready to be merged so you might want to wait a few more days.

Just fyi, #3431 is merged.

**Comment by mattijn** [comment] 2024-06-27 19:08
> cc @mattijn, I would personally prefer this approach to making pandas optional, but interested to hear your thoughts.

We like it when Altair is lightweight and dataframe agnostic.

We have experimented with adopting the dataframe interchange protocol through relying on `pyarrow.interchange.from_dataframe` to reach that goal.

Eventhough the interface protocol brought us a lot in relation to becoming dataframe agnostic, but not all (ref #3377) and unfortunately pyarrow is not a library that makes Altair lightweight. 

If there are better options to become dataframe agnostic and lightweight by not having hard dependencies on heavy dataframe packages, than it seems like something to consider seriously. 

If we found out that column type inference and data serialization for objects that are like dataframes can be delegated safely to narwhals, than it at least is something we should consider as a potential candidate.

I say, 'like dataframes', because I don't think narwhals will supports arrays is it? (something we eventually hope to cover one day). Surely we aim not to introduce regressions during this consideration.

**Comment by MarcoGorelli** [comment] 2024-07-02 15:16
> Could we jump straight to supporting polars without pyarrow using narwhals?

Here we go 🚀 https://github.com/vega/altair/pull/3452 

I totally agree that it's an imperative that this would come with zero regressions. I'm not aware of any:

- pandas supported is unaffected
- pyarrow.Table is still supported
- Polars and Modin are supported natively, without needing either of the above
- Ibis (and other interchange protocol libraries) are still supported by going via PyArrow (so, there's no regression here)

> I don't think narwhals will supports arrays is it?

That's right, arrays are a different beast - I'd suggest taking a look at https://data-apis.org/array-api/latest/ for that. Array libraries were sufficiently aligned to begin with that a standard like that was possible and successful, whereas for dataframes the related effort was discontinued (and that's how Narwhals was born - I'm not calling it a "standard", but I am trying to use my position as pandas + Polars dev to enable libraries to support the latter at no cost to the former)

---

I think a consideration that will come up will be "can we trust Narwhals? Will it stay maintained? Will it make breaking changes". If so, these would be totally valid :)
- Regarding maintainability, there are other major libraries considering using Narwhals ([scikit-learn](https://github.com/scikit-learn/scikit-learn/pull/28513#issuecomment-2131226993), [shiny](https://github.com/narwhals-dev/narwhals/issues/259#issuecomment-2192736446)), so I think there's enough interested parties such that, if we set up a good governance model, it could thrive even if I disappeared. I've already given write and admin access to some people I trust and who have made really solid contributions
- Regarding breaking changes: we're aiming for a "perfect backwards compatibility" policy in Narwhals, inspired by Rust Editions, see [this RFC](https://github.com/narwhals-dev/narwhals/issues/259#issuecomment-2194324064)

**Comment by binste** [comment] 2024-07-02 18:30
> I think a consideration that will come up will be "can we trust Narwhals? Will it stay maintained? Will it make breaking changes". If so, these would be totally valid :)
> 
> * Regarding maintainability, there are other major libraries considering using Narwhals ([scikit-learn](https://github.com/scikit-learn/scikit-learn/pull/28513#issuecomment-2131226993), [shiny](https://github.com/narwhals-dev/narwhals/issues/259#issuecomment-2192736446)), so I think there's enough interested parties such that, if we set up a good governance model, it could thrive even if I disappeared. I've already given write and admin access to some people I trust and who have made really solid contributions
> * Regarding breaking changes: we're aiming for a "perfect backwards compatibility" policy in Narwhals, inspired by Rust Editions, see [this RFC](https://github.com/narwhals-dev/narwhals/issues/259#issuecomment-2194324064)

Thanks for addressing this proactively. If other major libraries use it and if it has such a compatibility policy, that does definitely provide some comfort. In addition, Altair does not have that much data transformation logic built in. So even if for whatever reason we would need to remove the dependency on Narwhals again, I think that would be doable in a weekend :) To me the project looks well structured, documented, and the best shot we have. The alternative would be to implement different code paths ourselves.

**Closed** 2024-07-15 17:46 UTC
Labels: enhancement
