### ISSUE TITLE
Saving from the interface is different from Chart.save

### ISSUE THREAD

**Issue by mauruscz** [vega/altair#3192] opened 2023-09-18 11:35 UTC
Hi,

After several trials I managed to set a "saving" framework, so I am now able to save my plots as svg/png. Nevertheless, when I save it from the interface (i.e. clicking "save as svg") the saved plot is the same as the one that I visualize in the jupyter cell, that is what I would expect. 
Instead, when I do it executing the `chart.save() ` command, the resulting plot is smaller and I found no way for specifying a custom widht and height. Here it is an eample:

```
...
fig.title = "Plot number " +str(i)
fig.project(
        "transverseMercator",
        ).properties(
        width=1000,
        height=2000,
        ).configure_view(
        stroke=None
        )

fig.save("out/network_"+str(i)+".svg", engine = "vl-convert" )
```

I tryied adding a width/height parameter to the `save()` method, or doing something like 
```
fig.properties(
        width=1000,
        height=2000,
)

```

But sill I obtain a really small and squared svg/png file.

Is it a bug or am I missing something? 

Thank you very much

**Comment by jonmmease** [comment] 2023-09-18 11:53
Thanks for the report. I think what's happening is that Altair methods like `chart.project()` and `chart.properties()` return new copies of the chart with the changes applied. Then don't modify the chart that the method is called on.

So instead of something like this:

```python
chart = alt.Chart(...).mark(...).encode(...)
chart.properties(...)
chart.save()
```

You want
```python
chart = alt.Chart(...).mark(...).encode(...)
chart = chart.properties(...)
chart.save()
```

Does that work for you?  If not, could you provide a full minimal example that can be copied and evaluated without modification?

**Comment by mauruscz** [comment] 2023-09-18 12:08
Thank you for your fast and precise answer. Indeed, it is working! I hope you can be able to fix the saving in pdf for the altair version >5 asap, because the library rocks!

**Comment by mauruscz** [comment] 2023-09-18 13:07
Yes, it is! I am a researcher within the human mobility analysis field (we also mantain a library), so the final goal would be to have an high resolution image ready for publications.
 
In this direction, it would be wonderful to have the possibility of drawing "edges" of a network, (graphically, drawing directed vectors).

**Comment by joelostblom** [comment] 2023-09-21 02:01
In terms of network drawings in altair, there used to be this project which seems to have halted now https://github.com/Zsailer/nx_altair. But maybe there is something that can still be used from there?

**Comment by YuliaGaz** [comment] 2024-06-14 11:54
Hello!
I have a similar issue as the original one, but it is not solved by applying methods in another way.
I met it on some big complex dataset, and reducing it to the minimal reproducing example will take some time, but maybe somebody will understand the reason even without it. 

My problem: saving chart from jupyter interface saves it as it is shown in the notebook. But if I use chart.save(), the resulting plot is lacking borders on some elements of the plot. See the screenshots with pieces of the chart please:
1. Saved from jupyter interface:
![saved from interface](https://github.com/vega/altair/assets/88091115/a96abb7a-3e23-4a6f-a6a6-62d5d3cc2496)
2. Saved with chart.save() 
![saved with save](https://github.com/vega/altair/assets/88091115/12141c73-fe15-47bc-aa63-40d5091e584d)

Code, for generating this plot:
`heatmap = alt.Chart(x).mark_rect(stroke='w', strokeWidth=1).encode(
    x = alt.X('weeks_in_study_AT:N', title = x_title),
    y = alt.Y("participant:N", title = "Participant", sort=alt.EncodingSortField(field="order")),
    color = alt.Color("Active_tests_adherence:N", title = "",
                      scale = alt.Scale(domain=domain_AT, range = range_colors))
).properties(
    width=750,
    height=500
).configure_axis(
    labelFontSize=12,
    titleFontSize=20
).configure_legend(
    titleFontSize=14,
    labelFontSize=14
).configure_view(
    fill = 'white'
)

# Draw the chart
heatmap
heatmap.save(os.path.join(results, "heatmap_adherence_AT.png"))`

Thank you in advance guys!

**Comment by joelostblom** [comment] 2024-06-14 12:14
@YuliaGaz This is happening because you use `'w'` which is not a valid HTML color code. If you change to `'white'`, it will work as accepted. Ideally an error would be raised when string is used that doesn't match an HTML color code, but this would need to happen in VegaLite. I'll close this since the original issue (and hopefully your issue) has been resolved.

**Closed by joelostblom** 2024-06-14 12:14 UTC
Labels: bug

**Comment by YuliaGaz** [comment] 2024-06-14 14:24
Thank you @joelostblom 
I will try it today!
